### ISSUE TITLE
Update landing page titles for pages in multi-page categories

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#942]
This is a follow-up to https://github.com/uswds/uswds-site/pull/932#issuecomment-623687928.

Even on desktop, I think it's unclear whether repeating the category name for the landing page helps clarify the purpose of the page.

**Comment by KimberlyHodges** [comment]
@afeijoo it looks like this has been resolved.

**Comment by afeijoo** [comment]
@KimberlyHodges This isn't resolved. Here are two stories, which I think get at the essence of Dan's comment in https://github.com/uswds/uswds-site/pull/932#issuecomment-623687928.

**Story 1. Mobile Visitor**

As a mobile visitor to https://designsystem.digital.gov/
I want to see unique navigation labels 
So I understand what's on the page

There are currently duplicate labels on mobile:

<img width="618" alt="Screen Shot 2020-05-26 at 3 05 29 PM" src="https://user-images.githubusercontent.com/400690/82940155-68acfc00-9f62-11ea-9fdb-ccfd62ae4c3c.png">

---

**Story 2. Desktop Visitor**

As a desktop visitor to https://designsystem.digital.gov/
I don't want to see navigation label repeated in the sidebar
So I can easily distinguish between primary and secondary navigation.

The top nav currently repeats in the side nav:

<img width="1281" alt="Screen Shot 2020-05-26 at 3 09 48 PM" src="https://user-images.githubusercontent.com/400690/82940547-0274a900-9f63-11ea-9fe2-5f5cd3bdc2f9.png">

**Comment by KimberlyHodges** [comment]
@afeijoo and @mejiaj  @thisisdano  - curent status based on ny review of desktop, all of the primary landing pages are consistently labled meaning Primary Navigiation Label, URl, Page Name and Left Nav lable all indicate consitently where I am on the site. By doing so, we ended up duping primary nav lables in mobile. 
1. We want consistency in how the navigation functions in mobile. Right now Design Principles and Page Templates are single pages and provide a somewhat jarring experience simply because there's no sub nav. 
2. In addition, we now have duplciate lables for all other sections in mobile. @afeijoo do we have data on number of mobile users? We still need to address the issue, but I'm trying to help us prioritize this. 
Using Design Tokens as an example, we need to reconcile these three labels (pages?) into a single page, single label. 
<img width="483" alt="Screen Shot 2020-05-27 at 10 15 32 AM" src="https://user-images.githubusercontent.com/56093921/83034074-d827f780-a005-11ea-8e05-001ecddbc25d.png">
@nks-bix can you set up a separte working meeting for us to discuss. That seems the most effcient way to discuss: addressing the usability issues, level of difficulity to make the updates consistently accross the site and potential gain.
